# Generated by Django 5.0.3 on 2024-03-06 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField()),
                ('content', models.CharField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
