# Generated by Django 5.0.3 on 2024-03-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeleap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Codeleap',
        ),
    ]
